# Regenerates the display-mode .bat files from the .cfg layouts next to this script.
#
# Run this whenever you re-save one of the .cfg files from the MultiMonitorTool GUI.
# The bats contain a /SetMonitors line whose geometry is copied out of the matching
# cfg, so if the cfg changes and this is not re-run, the bat will fight your new
# layout instead of applying it.
#
#   powershell -ExecutionPolicy Bypass -File "D:\Programs\multimonitortool-x64\regenerate-modes.ps1"

$d = "D:\Programs\multimonitortool-x64"
$g = '{4d36e96e-e325-11ce-bfc1-08002be10318}'

$ID = @{
  EDR = "MONITOR\EDR2380\$g\0006"
  AOC = "MONITOR\AOC2269\$g\0008"
  SAC = "MONITOR\SAC2453\$g\0002"
  MTT = "MONITOR\MTT1337\$g\0013"
}

function Read-Cfg($path) {
  $sections = @{}; $cur = $null
  foreach ($line in [IO.File]::ReadAllLines($path)) {
    $l = $line.Trim()
    if ($l -match '^\[(.+)\]$') { $cur = $matches[1]; $sections[$cur] = @{} ; continue }
    if ($cur -and $l -match '^([^=]+)=(.*)$') { $sections[$cur][$matches[1]] = $matches[2] }
  }
  $sections
}

function Spec($mid, $e) {
  "Name=$mid BitsPerPixel=$($e.BitsPerPixel) Width=$($e.Width) Height=$($e.Height) " +
  "DisplayFlags=$($e.DisplayFlags) DisplayFrequency=$($e.DisplayFrequency) " +
  "DisplayOrientation=$($e.DisplayOrientation) PositionX=$($e.PositionX) PositionY=$($e.PositionY)"
}

function Build-PhysicalMode($cfgName, $batName, $wallpaperPairs) {
  $cfg = Read-Cfg (Join-Path $d $cfgName)

  $specs = @(); $primary = $null
  foreach ($key in 'EDR','AOC','SAC') {
    $mid = $ID[$key]
    $entry = $null
    foreach ($s in $cfg.Values) { if ($s.MonitorID -eq $mid) { $entry = $s; break } }
    if (-not $entry) { Write-Output "  WARN: $key not found in $cfgName"; continue }
    if ([int]$entry.Width -gt 0) { $specs += '"' + (Spec $mid $entry) + '"' }
    if ($entry.PositionX -eq '0' -and $entry.PositionY -eq '0') { $primary = $mid }
  }
  if (-not $primary) { $primary = $ID.SAC; Write-Output "  WARN: no monitor at 0,0 in $cfgName - primary defaulted to SAC2453" }

  $wp = ($wallpaperPairs | ForEach-Object { "$($_[0]) `"$($_[1])`"" }) -join ' '

  $b = @"
@echo off
rem GENERATED by regenerate-modes.ps1 from $cfgName - do not hand-edit the
rem /SetMonitors line below; change $cfgName and re-run the script instead.
cd /d "$d"

rem Re-attach the physical panels. iPad mode disconnects them, and a disconnected
rem display exposes no Monitor ID, so MultiMonitorTool cannot address it at all -
rem only this Windows-level call brings it back into the topology first.
DisplaySwitch.exe /extend
ping -n 9 127.0.0.1 >nul

rem Then enable each one SEPARATELY. In a single /enable call, one monitor that is
rem missing (asleep, unplugged) makes the whole command fail silently and every
rem step below it cascades.
multimonitortool.exe /enable "$($ID.EDR)"
ping -n 3 127.0.0.1 >nul
multimonitortool.exe /enable "$($ID.AOC)"
ping -n 3 127.0.0.1 >nul
multimonitortool.exe /enable "$($ID.SAC)"
ping -n 5 127.0.0.1 >nul

rem Move primary onto a physical panel BEFORE dropping the virtual display -
rem Windows refuses to disable whichever monitor is currently primary.
multimonitortool.exe /SetPrimary "$primary"
ping -n 4 127.0.0.1 >nul
multimonitortool.exe /disable "$($ID.MTT)"
ping -n 5 127.0.0.1 >nul

multimonitortool.exe /LoadConfig "$cfgName"
ping -n 6 127.0.0.1 >nul

rem Config files do not record which display is primary, and LoadConfig always
rem re-anchors the layout on EDR2380. So SetPrimary must run again AFTER it.
multimonitortool.exe /SetPrimary "$primary"
ping -n 4 127.0.0.1 >nul

rem DUPLICATES $cfgName ON PURPOSE. LoadConfig alone does not restore rotation or
rem refresh rate, and anchors positions off the wrong monitor. These values were
rem copied from $cfgName by regenerate-modes.ps1 - re-run it if you edit the cfg.
multimonitortool.exe /SetMonitors $($specs -join ' ')
ping -n 5 127.0.0.1 >nul

rem One pass, no --primary. Every monitor is named explicitly here, so the global
rem SPI repaint has nothing to fall back for - and it lands last and overwrites
rem whichever monitor is primary, which is what kept replacing dell.jpg.
SetWallpaper.exe $wp
"@
  [IO.File]::WriteAllText((Join-Path $d $batName), ($b -replace "`r?`n","`r`n"))
  $pname = ($ID.GetEnumerator() | Where-Object { $_.Value -eq $primary }).Key
  Write-Output "wrote $batName  (primary=$pname, $($specs.Count) monitor specs)"
}

$edra = 'D:\333\edra.png'; $aoc = 'D:\333\aoc.png'; $dell = 'D:\333\dell.jpg'

$base = @( ,@('EDR2380',$edra) )
$base += , @('AOC2269',$aoc)
$base += , @('SAC2453',$dell)

$wpSamsung = $base + (, @('UID257','D:\333\samsung.jpg'))
$wpIpad    = $base + (, @('UID256','D:\333\ipadasmonitor.jpg'))
$wpIpadLap = $wpIpad + (, @('UID258','D:\333\ipadlaptoasmonitor.png'))

Build-PhysicalMode '3_monitors.cfg'          'SLOPTOP MODE.bat'               $base
Build-PhysicalMode 'samsungasmonitor.cfg'    'SAMSUNGasmonitor.bat'           $wpSamsung
Build-PhysicalMode 'ipadasmonitor.cfg'       'iPad as Monitor.bat'            $wpIpad
Build-PhysicalMode 'ipadlaptopasmonitor.cfg' 'iPad and Laptop as Monitor.bat' $wpIpadLap

# Wallpaper-only helper, same single-pass rule.
$setwp = @"
@echo off
rem GENERATED by regenerate-modes.ps1
cd /d "$d"
rem No --primary: see the note in the generated mode bats.
SetWallpaper.exe $(($base | ForEach-Object { "$($_[0]) `"$($_[1])`"" }) -join ' ')
"@
[IO.File]::WriteAllText("$d\Set Wallpapers.bat", ($setwp -replace "`r?`n","`r`n"))
Write-Output "wrote Set Wallpapers.bat"
