@echo off
rem GENERATED by regenerate-modes.ps1
cd /d "D:\Programs\multimonitortool-x64"
rem No --primary: see the note in the generated mode bats.
SetWallpaper.exe EDR2380 "D:\333\edra.png" AOC2269 "D:\333\aoc.png" SAC2453 "D:\333\dell.jpg"